name: github actions

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker login
        uses: docker/login-action@v3
        with:
          username: naveenmadhav
          password: dckr_pat_YxISFNbEEbgzhpjUD07h_4ERgnI
      -
        name: Docker setup
        uses: docker/setup-buildx-action@v3
      -
        name: Build 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: naveenmadhav/chatlog:latest